// Vocabulário lexical para ajudar o modelo de transcrição.
// Não incluir frases de replacement nem erros propositais de transcrição.
export const ULTRASOUND_TERMS = Object.freeze([
  // Classificações e comandos
  "Chammas I",
  "Chammas II",
  "Chammas III",
  "Chammas IV",
  "Chammas V",
  "Chammas 1",
  "Chammas 2",
  "Chammas 3",
  "Chammas 4",
  "Chammas 5",
  "TI-RADS",
  "TIRADS",
  "BI-RADS",
  "BIRADS",
  "BI-RADS 1",
  "BI-RADS 2",
  "BI-RADS 3",
  "BI-RADS 4-A",
  "FIGO",

  // Termos gerais de ultrassonografia
  "ultrassonografia",
  "ecografia",
  "Doppler",
  "Doppler colorido",
  "Dopplervelocimetria",
  "efeito Doppler",
  "fluxo ao Doppler",
  "vascularização",
  "vascularização central",
  "vascularização periférica",
  "avascularizado",
  "avascularizada",
  "ecogenicidade",
  "ecotextura",
  "hipoecogênico",
  "hipoecogênica",
  "hiperecogênico",
  "hiperecogênica",
  "ecogênico",
  "ecogênica",
  "anecóico",
  "anecóica",
  "anecoico",
  "anecoica",
  "heterogêneo",
  "heterogênea",
  "homogêneo",
  "homogênea",
  "contornos regulares",
  "contornos irregulares",
  "limites bem definidos",
  "limites precisos",
  "circunscrita",
  "não circunscrita",
  "reforço acústico posterior",
  "sombra acústica posterior",
  "atenuação acústica posterior",
  "fenômenos acústicos posteriores",
  "parênquima",
  "lateralidade",
  "medindo",
  "segmento",
  "lobo",
  "polo superior",
  "polo inferior",

  // Tireoide
  "tireoide",
  "tireóide",
  "istmo",
  "lobo direito",
  "lobo esquerdo",
  "nódulo",
  "nódulo sólido",
  "nódulo sólido-cístico",
  "nódulo misto",
  "nódulo espongiforme",
  "nódulo hipoecogênico",
  "nódulo hiperecogênico",
  "imagem nodular",
  "imagem nodular sólida",
  "cisto coloide",
  "vascularização tipo 1",
  "vascularização tipo 2",
  "vascularização tipo 3",
  "vascularização tipo 4",
  "nódulo texto padrão",
  "nódulo sólido tireoide",
  "fluxo aumentado",

  // Mama
  "mama",
  "mamas",
  "mamária",
  "mamaria",
  "tecido glandular",
  "retroareolar",
  "mamilo",
  "quadrante",
  "QSL",
  "QSE",
  "QSI",
  "QII",
  "nódulo mamário",
  "nódulo irregular",
  "lesão não nodular",
  "cisto simples",
  "aglomerado cístico",
  "microcistos",
  "microcístos",
  "linfonodo intramamário",
  "linfonodo intra-mamário",
  "ectasia ductal",
  "esteatonecrose",
  "siliconoma",
  "distorção arquitetural",
  "controle ultrassonográfico",
  "investigação histológica",

  // Ginecologia / Transvaginal
  "transvaginal",
  "pelve",
  "pélvica",
  "útero",
  "utero",
  "colo uterino",
  "cavidade endocervical",
  "endométrio",
  "endometrio",
  "cavidade endometrial",
  "miométrio",
  "miometrio",
  "ovário direito",
  "ovário esquerdo",
  "ovários",
  "anexial",
  "mioma",
  "miomatoso",
  "intramural",
  "adenomiose",
  "folículo",
  "foliculos",
  "folículos",
  "corpo lúteo",
  "corpo luteo",
  "pólipo endometrial",
  "pólipo endocervical",
  "cisto unilocular",
  "cisto hemorrágico",
  "endometrioma",
  "teratoma",
  "cisto dermoide",
  "ovários micropolicísticos",
  "hidrossalpinge",
  "DIU",
  "istmocele",
  "histerorrafia",
  "deiscência de cicatriz de histerorrafia",
  "hérnia de segmento",
  "útero bicorno",
  "mucométrio",
  "varizes pélvicas",

  // Abdome
  "abdome",
  "abdômen",
  "fígado",
  "figado",
  "vesícula biliar",
  "pólipo da vesícula",
  "pólipo na vesícula",
  "esteatose",
  "esteatose hepática",
  "esteatose leve",
  "esteatose moderada",
  "esteatose acentuada",
  "cisto hepático",
  "hemangioma",
  "rim direito",
  "rim esquerdo",
  "cisto renal",
  "cálculo renal",
  "cálculo no rim",
  "grupo calicinal",
  "angiomiolipoma",
  "cálculo biliar",
  "cálculo na vesícula",
  "colecistectomia",
  "ateromatose",
  "aorta abdominal",
]);
